import os

FORBIDDEN_USERNAMES = [
    "api",
    "main",
    "discover",
    "feed",
    "home",
    "auth",
    "shared_folders",
    "settings",
    "admin",
    "moderator",
    "support",
    "reset_password",
    "reset_password_request",
    "register",
    "logout",
    "login",
    "share_requests_received",
    "accept_share",
    "decline_share",
    "remove_inbound_share",
    "remove_outbound_share",
    "update_inbound_share",
    "remove_all_outbound_shares",
    "remove_all_inbound_shares",
    "follow",
    "approve_follow",
    "deny_follow",
    "request_follow",
    "cancel_request_follow",
    "unfollow",
    "search",
    "actions",
    "privacy_policy",
    "about_us",
    "about_extension",
    "documentation",
    "rename_folder",
    "copy_folder",
    "move_folder",
    "create_leaf",
    "query",
    "post",
    "posts",
    "tokens",
    "token",
    "pic_posts",
    "pic_post",
    "account",
    "folder",
    "stats",
    "followers",
    "following",
    "favorites",
    "follow_requests",
    "user",
    "p",
    "pic_folder",
]

# Path constants
APP_PATH = "app"

STATIC_PATH = os.path.join(APP_PATH, "static")

POST_PICS_PATH = os.path.join(STATIC_PATH, "post_pics")
PROFILE_PICS_PATH = os.path.join(STATIC_PATH, "profile_pics")
