"""adding display_name column on Users table

Revision ID: 003658387ecc
Revises: b7ca4675ef8f
Create Date: 2024-07-25 16:49:27.199530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003658387ecc'
down_revision = 'b7ca4675ef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_display_name'), ['display_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_display_name'))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
