"""topic name unique per parent not globally

Revision ID: 0a27bc4a71e6
Revises: 658f4de870aa
Create Date: 2026-03-21 22:16:24.108053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a27bc4a71e6'
down_revision = '658f4de870aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_name')
        batch_op.create_index(batch_op.f('ix_topic_name'), ['name'], unique=False)
        batch_op.drop_index('ix_topic_slug')
        batch_op.create_index(batch_op.f('ix_topic_slug'), ['slug'], unique=False)
        batch_op.create_unique_constraint('uq_topic_name_parent', ['name', 'parent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('uq_topic_name_parent', type_='unique')
        batch_op.drop_index(batch_op.f('ix_topic_slug'))
        batch_op.create_index('ix_topic_slug', ['slug'], unique=False)
        batch_op.drop_index(batch_op.f('ix_topic_name'))
        batch_op.create_index('ix_topic_name', ['name'], unique=False)

    # ### end Alembic commands ###
