"""add leaf table

Revision ID: 157cc8ff9b7f
Revises: 7d8f3e3856ee
Create Date: 2023-10-08 16:29:19.304907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157cc8ff9b7f'
down_revision = '7d8f3e3856ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaf',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=75), nullable=False),
    sa.Column('folder_path', sa.String(length=255), nullable=False),
    sa.Column('md_text', sa.String(length=8000), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'file_name', 'folder_path')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('sharer_folder_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('sharee_folder_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('sharee_folder_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('sharer_folder_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    op.drop_table('leaf')
    # ### end Alembic commands ###
