"""add dark mode

Revision ID: 169e95b936ab
Revises: 79030147cf1c
Create Date: 2023-10-07 23:37:24.114259

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "169e95b936ab"
down_revision = "79030147cf1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dark_mode", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("dark_mode")

    # ### end Alembic commands ###
