"""Created user_favorites tables

Revision ID: 177d68f057b5
Revises: 2a76831ffd3d
Create Date: 2023-09-08 18:36:21.862645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '177d68f057b5'
down_revision = '2a76831ffd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
