"""modify post and leaf table

Revision ID: 1adb995392a2
Revises: ea7beb2594d9
Create Date: 2024-07-28 19:36:21.107959

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1adb995392a2"
down_revision = "ea7beb2594d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaf", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_leaf_post", "post", ["post_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaf", schema=None) as batch_op:
        batch_op.drop_constraint("fk_leaf_post", type_="foreignkey")
        batch_op.drop_column("post_id")

    # ### end Alembic commands ###
