"""fix char len

Revision ID: 1ba746f75991
Revises: 169e95b936ab
Create Date: 2023-10-08 00:32:39.880703

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ba746f75991"
down_revision = "169e95b936ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.alter_column(
            "sharer_folder_path",
            existing_type=sa.VARCHAR(length=3000),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "sharee_folder_path",
            existing_type=sa.VARCHAR(length=3000),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.alter_column(
            "sharee_folder_path",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=3000),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "sharer_folder_path",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=3000),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
