"""user table updated to add verified field

Revision ID: 1bee8f53a9a0
Revises: 226ea758b7ed
Create Date: 2023-09-03 20:49:02.279365

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1bee8f53a9a0'
down_revision = '226ea758b7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
