"""increase posts link char length

Revision ID: 2a76831ffd3d
Revises: 1bee8f53a9a0
Create Date: 2023-09-06 12:20:25.109905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a76831ffd3d"
down_revision = "1bee8f53a9a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "link",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=2048),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "link",
            existing_type=sa.String(length=2048),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
