"""add follower requests table

Revision ID: 37f994a98042
Revises: 69c93cf81207
Create Date: 2023-09-12 18:08:10.915446

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37f994a98042'
down_revision = '69c93cf81207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower_requests',
    sa.Column('requestor_id', sa.Integer(), nullable=True),
    sa.Column('requestee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requestee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower_requests')
    # ### end Alembic commands ###
