"""posts table updated with favicon path

Revision ID: 3869244f6a92
Revises: 8147baab5118
Create Date: 2023-08-31 00:52:28.581816

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3869244f6a92'
down_revision = '8147baab5118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('favicon_path')

    # ### end Alembic commands ###
