"""followers

Revision ID: 4377b0823802
Revises: f04be08f1ea0
Create Date: 2023-06-21 16:04:21.613288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4377b0823802"
down_revision = "f04be08f1ea0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
