"""posts table updated with folder path

Revision ID: 56bb3d407487
Revises: 7c138554b69a
Create Date: 2023-08-29 12:57:29.346390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '56bb3d407487'
down_revision = '7c138554b69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
