"""add toggle color

Revision ID: 603df9491a7b
Revises: cb1bda890d30
Create Date: 2024-07-29 18:56:10.465817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603df9491a7b'
down_revision = 'cb1bda890d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_pic', schema=None) as batch_op:
        batch_op.drop_column('pic')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toggle_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('toggle_color')

    with op.batch_alter_table('post_pic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
