"""add agent_action and agent_query_log tables

Revision ID: 658f4de870aa
Revises: dfb0c1f4186b
Create Date: 2026-03-21 15:39:41.308775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658f4de870aa'
down_revision = 'dfb0c1f4186b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_action_canonical_url_id'), ['canonical_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_user_id'), ['user_id'], unique=False)

    op.create_table('agent_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_query_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_query_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_query_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_query_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_query_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_query_log_created_at'))

    op.drop_table('agent_query_log')
    with op.batch_alter_table('agent_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_action_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_canonical_url_id'))

    op.drop_table('agent_action')
    # ### end Alembic commands ###
