"""modify post and leaf table 2

Revision ID: 782daef9cfcc
Revises: 1adb995392a2
Create Date: 2024-07-28 19:45:58.661271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782daef9cfcc'
down_revision = '1adb995392a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    op.drop_table('_alembic_tmp_leaf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_leaf',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=75), nullable=False),
    sa.Column('folder_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('md_text', sa.VARCHAR(length=8000), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_leaf_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'file_name', 'folder_path')
    )
    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('favicon_file_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('folder_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('folder_link', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.Column('leaf_file_name', sa.VARCHAR(length=75), nullable=True),
    sa.Column('leaf_user_id', sa.INTEGER(), nullable=True),
    sa.Column('leaf_folder_path', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['leaf_user_id', 'leaf_file_name', 'leaf_folder_path'], ['leaf.user_id', 'leaf.file_name', 'leaf.folder_path'], name='fk_post_leaf'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
