"""create share table

Revision ID: 79030147cf1c
Revises: f9611d74912a
Create Date: 2023-10-06 14:16:51.533814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79030147cf1c"
down_revision = "f9611d74912a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shares",
        sa.Column("sharer_id", sa.Integer(), nullable=False),
        sa.Column("sharee_id", sa.Integer(), nullable=False),
        sa.Column("sharer_folder_path", sa.String(length=255), nullable=False),
        sa.Column("sharee_folder_path", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["sharee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sharer_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint(
            "sharer_id", "sharee_id", "sharer_folder_path", "sharee_folder_path"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shares")
    # ### end Alembic commands ###
