"""post table update

Revision ID: 7c138554b69a
Revises: 9c8e063555e0
Create Date: 2023-08-25 10:52:06.360637

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c138554b69a"
down_revision = "9c8e063555e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("link", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("link")

    # ### end Alembic commands ###
