"""fix char len 1

Revision ID: 7d8f3e3856ee
Revises: 1ba746f75991
Create Date: 2023-10-08 00:37:50.049484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d8f3e3856ee'
down_revision = '1ba746f75991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_requests', schema=None) as batch_op:
        batch_op.alter_column('shared_folder_path',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_requests', schema=None) as batch_op:
        batch_op.alter_column('shared_folder_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)

    # ### end Alembic commands ###
