"""posts table updated with folder name

Revision ID: 8147baab5118
Revises: 56bb3d407487
Create Date: 2023-08-29 16:27:49.241977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8147baab5118'
down_revision = '56bb3d407487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('folder_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('folder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('folder_link')
        batch_op.drop_column('folder_name')

    # ### end Alembic commands ###
