"""add agent intelligence infrastructure

Revision ID: 8554c4ab19be
Revises: 88fa7a16d4d6
Create Date: 2026-03-20 21:18:32.200184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8554c4ab19be'
down_revision = '88fa7a16d4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=4096), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('global_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_url_canonical_url'), ['canonical_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_canonical_url_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_url_url_hash'), ['url_hash'], unique=True)

    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_topic_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_slug'), ['slug'], unique=True)

    op.create_table('agent_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('api_key_created', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('agent_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_profile_api_key'), ['api_key'], unique=True)

    op.create_table('domain_credibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'topic_id', name='uq_domain_topic')
    )
    with op.batch_alter_table('domain_credibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_credibility_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_credibility_topic_id'), ['topic_id'], unique=False)

    op.create_table('topic_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_alias_alias_name'), ['alias_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_alias_topic_id'), ['topic_id'], unique=False)

    op.create_table('topic_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('webhook_secret', sa.String(length=128), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_delivered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_sub')
    )
    with op.batch_alter_table('topic_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_subscription_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('url_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('relevance_justification', sa.Text(), nullable=True),
    sa.Column('source_credibility', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_metadata_canonical_url_id'), ['canonical_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_metadata_submitted_by'), ['submitted_by'], unique=False)

    op.create_table('url_propagation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_in_topic', sa.DateTime(), nullable=True),
    sa.Column('submission_velocity', sa.Float(), nullable=True),
    sa.Column('peak_velocity_at', sa.DateTime(), nullable=True),
    sa.Column('first_submitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.ForeignKeyConstraint(['first_submitted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url_id', 'topic_id', name='uq_url_topic_prop')
    )
    with op.batch_alter_table('url_propagation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_propagation_canonical_url_id'), ['canonical_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_propagation_topic_id'), ['topic_id'], unique=False)

    op.create_table('url_topic_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('first_tagged_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url_id', 'topic_id', name='uq_url_topic')
    )
    with op.batch_alter_table('url_topic_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_topic_score_canonical_url_id'), ['canonical_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_topic_score_topic_id'), ['topic_id'], unique=False)

    op.create_table('agent_trust_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('related_topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['related_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trust_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trust_event_user_id'), ['user_id'], unique=False)

    op.create_table('post_topic_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('tagged_by', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tagged_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'topic_id', 'tagged_by', name='uq_post_topic_tagger')
    )
    with op.batch_alter_table('post_topic_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_topic_tag_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_topic_tag_tagged_by'), ['tagged_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_topic_tag_topic_id'), ['topic_id'], unique=False)

    op.create_table('webhook_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['topic_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_subscription_id'), ['subscription_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_url_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_canonical_url_id'), ['canonical_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_content_hash'), ['content_hash'], unique=False)
        batch_op.create_foreign_key('fk_post_canonical_url', 'canonical_url', ['canonical_url_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_agent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trust_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_contributions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_contributions')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('is_agent')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_content_hash'))
        batch_op.drop_index(batch_op.f('ix_post_canonical_url_id'))
        batch_op.drop_column('content_hash')
        batch_op.drop_column('canonical_url_id')

    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_subscription_id'))

    op.drop_table('webhook_delivery')
    with op.batch_alter_table('post_topic_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_topic_tag_topic_id'))
        batch_op.drop_index(batch_op.f('ix_post_topic_tag_tagged_by'))
        batch_op.drop_index(batch_op.f('ix_post_topic_tag_post_id'))

    op.drop_table('post_topic_tag')
    with op.batch_alter_table('agent_trust_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trust_event_user_id'))

    op.drop_table('agent_trust_event')
    with op.batch_alter_table('url_topic_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_topic_score_topic_id'))
        batch_op.drop_index(batch_op.f('ix_url_topic_score_canonical_url_id'))

    op.drop_table('url_topic_score')
    with op.batch_alter_table('url_propagation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_propagation_topic_id'))
        batch_op.drop_index(batch_op.f('ix_url_propagation_canonical_url_id'))

    op.drop_table('url_propagation')
    with op.batch_alter_table('url_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_metadata_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_url_metadata_canonical_url_id'))

    op.drop_table('url_metadata')
    with op.batch_alter_table('topic_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_subscription_topic_id'))

    op.drop_table('topic_subscription')
    with op.batch_alter_table('topic_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_alias_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_alias_alias_name'))

    op.drop_table('topic_alias')
    with op.batch_alter_table('domain_credibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_credibility_topic_id'))
        batch_op.drop_index(batch_op.f('ix_domain_credibility_domain'))

    op.drop_table('domain_credibility')
    with op.batch_alter_table('agent_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_profile_api_key'))

    op.drop_table('agent_profile')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_slug'))
        batch_op.drop_index(batch_op.f('ix_topic_path'))
        batch_op.drop_index(batch_op.f('ix_topic_parent_id'))
        batch_op.drop_index(batch_op.f('ix_topic_name'))

    op.drop_table('topic')
    with op.batch_alter_table('canonical_url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_url_url_hash'))
        batch_op.drop_index(batch_op.f('ix_canonical_url_domain'))
        batch_op.drop_index(batch_op.f('ix_canonical_url_canonical_url'))

    op.drop_table('canonical_url')
    # ### end Alembic commands ###
