"""fix display_name unique bug

Revision ID: 88fa7a16d4d6
Revises: 93a215e7829b
Create Date: 2024-08-08 16:32:17.712118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fa7a16d4d6'
down_revision = '93a215e7829b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_display_name', ['display_name'], unique=False)

    # ### end Alembic commands ###
