"""posts table

Revision ID: 8d7ac41fef2e
Revises: b5fbd3eb143d
Create Date: 2023-06-20 13:56:59.720555

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d7ac41fef2e"
down_revision = "b5fbd3eb143d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=140), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_timestamp"))

    op.drop_table("post")
    # ### end Alembic commands ###
