"""add description to post

Revision ID: ab883e3174e4
Revises: dd32df4b07fe
Create Date: 2024-07-20 14:48:22.715883

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab883e3174e4"
down_revision = "dd32df4b07fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=140), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
