"""add description text color field fix

Revision ID: b7ca4675ef8f
Revises: d87d6131cd93
Create Date: 2024-07-20 17:48:48.057475

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7ca4675ef8f"
down_revision = "d87d6131cd93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "description_text_color",
            existing_type=sa.BOOLEAN(),
            type_=sa.String(10),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "description_text_color",
            existing_type=sa.String(10),
            type_=sa.BOOLEAN(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
