"""Add share requests table

Revision ID: b7fe978ee4d3
Revises: 37f994a98042
Create Date: 2023-10-06 02:50:21.063462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fe978ee4d3'
down_revision = '37f994a98042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_requests',
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('requestee_id', sa.Integer(), nullable=False),
    sa.Column('shared_folder_path', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['requestee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('requestor_id', 'requestee_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('folder_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('favicon_file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('favicon_file_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('folder_link',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('share_requests')
    # ### end Alembic commands ###
