"""add PostPic model

Revision ID: cb1bda890d30
Revises: 1adb995392a2
Create Date: 2024-07-29 14:13:47.187727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1bda890d30'
down_revision = '1adb995392a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_pic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('folder_name', sa.String(length=255), nullable=True),
    sa.Column('folder_link', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_pic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_pic_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_pic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_pic_timestamp'))

    op.drop_table('post_pic')
    # ### end Alembic commands ###
