"""add description text color field

Revision ID: d87d6131cd93
Revises: ab883e3174e4
Create Date: 2024-07-20 17:26:24.670073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d87d6131cd93"
down_revision = "ab883e3174e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description_text_color", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("description_text_color")

    # ### end Alembic commands ###
