"""add url_embedding table

Revision ID: dfb0c1f4186b
Revises: 8554c4ab19be
Create Date: 2026-03-20 23:06:56.610729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb0c1f4186b'
down_revision = '8554c4ab19be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('vector', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_embedding_canonical_url_id'), ['canonical_url_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_embedding_canonical_url_id'))

    op.drop_table('url_embedding')
    # ### end Alembic commands ###
