"""new fields in user model

Revision ID: f04be08f1ea0
Revises: 8d7ac41fef2e
Create Date: 2023-06-21 13:39:17.907404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f04be08f1ea0"
down_revision = "8d7ac41fef2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
