"""fix share requests table 1

Revision ID: f9611d74912a
Revises: b7fe978ee4d3
Create Date: 2023-10-06 03:02:29.349504

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9611d74912a"
down_revision = "b7fe978ee4d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("share_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "shared_folder_path", existing_type=sa.VARCHAR(length=3000), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("share_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "shared_folder_path", existing_type=sa.VARCHAR(length=3000), nullable=True
        )

    # ### end Alembic commands ###
