"""posts table favicon path now called favicon_file_name

Revision ID: fa9ac5426d07
Revises: 3869244f6a92
Create Date: 2023-08-31 01:37:09.279403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9ac5426d07'
down_revision = '3869244f6a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_file_name', sa.String(length=255), nullable=True))
        batch_op.drop_column('favicon_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('favicon_file_name')

    # ### end Alembic commands ###
